### ISSUE TITLE
reporting Docusaurus error 

### ISSUE THREAD

**Issue by GeoGerrit** [equinor/completor#107]
See screenshot

![image](https://github.com/equinor/completor/assets/45842747/6f0849f0-cefa-4e62-93fb-2a330a23c820)

## Describe the bug
*A clear and concise description of what the bug is.*

### **To Reproduce**
*Describe how to reproduce the bug.
Are you able to trim down the problem to make it as simple as possible?
Are you able to distinguish between when it is working, and when it is not?
The smaller the problem and input data, the easier it is to debug and find the error.*

### **Expected behavior**
*What do you expect to happen?*

### **Debug info**
*If applicable, run the cli with the argument "-l=DEBUG" and provide the output.
Verify that there is no sensitive information in output, anonymize if needed.*

**Comment by hrsut** [comment]
closed #105
