### ISSUE TITLE
Double check if test removal is ok

### ISSUE THREAD

**Issue by MegaAnda123** [equinor/completor#142]
Remove test related to issue [#93](https://github.com/equinor/subscript-internal/issues/93) in subscript-internal repo.
What is the issue? What did the test check? @cutn94 @hrsut

**Comment by cutn94** [comment]
I looked at this case and it is created to solve a bug that is related to the duplicate segments. This test case seems to be problem-specific. Do we usually keep problem-specific test in the repo for testing? @Aleksander-Karlsson do u still remember this issue?
